services:
  doyou-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doyou-server
    ports:
      - "8080:8080"
    environment:
      - FFMPEG_LOCATION=/usr/bin/ffmpeg
    restart: unless-stopped
