[project]
name = "src-oxapy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "google-api-python-client>=2.186.0",
    "oxapy>=0.6.7",
    "python-dotenv>=1.2.1",
    "yt-dlp==2025.10.14",
]
